### ISSUE TITLE
Does not seem to work with pnpm

### ISSUE THREAD

**Issue by fabrizionastri** [BayBreezy/nuxt3-vuetify3-starter#4]
I just downloaded your repo and did a "pnpm install" which gave me this warning:

```
PS C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter> pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> @ postinstall C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter
> nuxt prepare

Nuxi 3.4.2                                                                                                                                           16:29:19

[16:29:22]  WARN  Duplicated imports "usePWAIcon", the one from "C:/Users/fabri/Repos/_courses/vuetify/_sources/nuxt3-vuetify3-starter/node_modules/.pnpm/@kevinmarrec+nuxt-pwa@0.17.0/node_modules/@kevinmarrec/nuxt-pwa/dist/runtime/composables/usePWAIcon.d.ts" has been ignored

✔ Types generated in .nuxt                                                                                                                           16:29:22
Done in 4.1s
```

When I then tried to launch the app with a pnpm dev, I got these errors and warnings:

```
S C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter> pnpm install

Nuxi 3.4.2                                                                                                                                           16:31:16  
Nuxt 3.4.2 with Nitro 2.6.3                                                                                                                          16:31:16
                                                                                                                                                     16:31:18
  > Local:    http://localhost:3000/ 
  > Network:  http://172.18.96.1:3000/                                                                                                               16:31:16  
  > Network:  http://192.168.1.90:3000/
  > Network:  http://192.168.56.1:3000/
  > Network:  http://[2a01:e0a:18a:cb20:35c3:c596:368:f1d0]:3000/
  > Network:  http://[2a01:e0a:18a:cb20:ecde:cdb1:f846:d824]:3000/

[16:31:19]  WARN  Duplicated imports "usePWAIcon", the one from "C:/Users/fabri/Repos/_courses/vuetify/_sources/nuxt3-vuetify3-starter/node_modules/.pnpm/@kevinmarrec+nuxt-pwa@0.17.0/node_modules/@kevinmarrec/nuxt-pwa/dist/runtime/composables/usePWAIcon.d.ts" has been ignored

✔ PWA icons generated in 2446 ms                                                                                                                    16:32:19
ℹ Vite client warmed up in 106ms                                                                                                                    16:32:19

[16:32:19]  ERROR  Failed to resolve import "vue" from "virtual:nuxt:C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\.nuxt\components.client.mjs". Does the file exist?

[16:27:34]  ERROR  Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.4.2_@types+node@18.17.19_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js?v=141a6b2a". Does the file exist? (x2)

[16:27:34]  ERROR  Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.4.2_@types+node@18.17.19_sass@1.68.0\node_modules\nuxt\dist\pages\runtime\plugins\router.js?v=141a6b2a". Does the file exist?

[16:27:35]  ERROR  Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.4.2_@types+node@18.17.19_sass@1.68.0\node_modules\nuxt\dist\app\components\nuxt-root.vue". Does the file exist?

[16:27:35]  ERROR  Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.4.2_@types+node@18.17.19_sass@1.68.0\node_modules\nuxt\dist\app\components\utils.js?v=141a6b2a". Does the file exist? (x2)

[16:27:35]  ERROR  Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.4.2_@types+node@18.17.19_sass@1.68.0\node_modules\nuxt\dist\pages\runtime\utils.js?v=141a6b2a". Does the file exist?"
```

I then removed the node_modules and tried again to install with npm (instead of pnpm), with "npm install" followed by "npm run dev". I got some more warnings and errors, so I did a "npm audit --fix force" which updated the package.json file to:
```

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "reset": "rm -rf .nuxt node_modules .output package-lock.json && npm install",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@iconify/vue": "^4.1.1",
    "@kevinmarrec/nuxt-pwa": "^0.17.0",
    "@nuxtjs/google-fonts": "^3.0.0",
    "nuxt": "3.4.2",
    "sass": "^1.62.0",
    "vuetify": "^3.1.15"
  },
  "dependencies": {
    "vite-plugin-vuetify": "^1.0.2"
  }
}
```

To 
```

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "reset": "rm -rf .nuxt node_modules .output package-lock.json && npm install",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@iconify/vue": "^4.1.1",
    "@kevinmarrec/nuxt-pwa": "^0.17.0",
    "@nuxtjs/google-fonts": "^3.0.2",
    "nuxt": "^3.7.3",
    "sass": "^1.68.0",
    "vuetify": "^3.3.17"
  },
  "dependencies": {
    "vite-plugin-vuetify": "^1.0.2",
    "vue": "^3.3.4"
  }
}
```

After this change, "npm install" and "npm dev" worked fine.

I them removed the node_modules again and tried again with pnpm. I did a "pnpm install" followed by "pnpm dev". This time I got these error messages:

```
C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter> pnpm run dev

> dev
> nuxt dev

Nuxt 3.7.3 with Nitro 2.6.3                                                                                                                          17:17:03
                                                                                                                                                     17:17:03
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✔ PWA icons generated in 856 ms                                                                                                                     17:17:08
ℹ Vite client warmed up in 12960ms                                                                                                                  17:17:22
✔ Nitro built in 2605 ms                                                                                                                      nitro 17:17:24
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function
  at setup (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\pages\runtime\plugins\router.js:46:258)
  at C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:114:60 

  at fn (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:162:44)
  at Object.callAsync (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\unctx:68:55)
  at C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:164:56 

  at Object.runWithContext (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3855:18)
  at callWithNuxt (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:164:24)
  at Object.runWithContext (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:34:29)
  at applyPlugin (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:114:39)
  at Module.applyPlugins (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:130:21)
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function
  at setup (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\pages\runtime\plugins\router.js:46:258)
  at C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:114:60 

  at fn (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:162:44)
  at Object.callAsync (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\unctx:68:55)
  at C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:164:56 

  at Object.runWithContext (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3855:18)
  at callWithNuxt (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:164:24)
  at Object.runWithContext (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:34:29)
  at applyPlugin (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:114:39)
  at Module.applyPlugins (C:\Users\fabri\Repos\_courses\vuetify\_sources\nuxt3-vuetify3-starter\node_modules\.pnpm\nuxt@3.7.3_sass@1.68.0\node_modules\nuxt\dist\app\nuxt.js:130:21)
```

**Comment by BayBreezy** [comment]
Hello @fabrizionastri , I have never tested this with pnpm XD but I will look into it.
The initial error has something to do with the PWA module it seems. This module was added for the SEO stuff by me initially. It can be removed. Can you try removing ti and see if you still get the error?

**Comment by fabrizionastri** [comment]
Hi @BayBreezy , thanks for the prompt reply. I just removed the following:
- in package.json: `"@kevinmarrec/nuxt-pwa": "^0.17.0",`
- in nuxt.config.ts: the whole modules bloc:
   ```
  modules: [
      // "@kevinmarrec/nuxt-pwa",
      async (options, nuxt) => {
        nuxt.hooks.hook("vite:extendConfig", (config) => {
          config.plugins ||= []
          config.plugins.push(vuetify())
        });
      },
    ],
  ```

But I stil l have the same error messages.

**Comment by BayBreezy** [comment]
@fabrizionastri Sooo.. after a few hours of digging, I see where the only way to get the Vuetify stuff to work with pnpm in nuxt is to add the `.npmrc` file to the root of your project and add this line `shamefully-hoist=true`.

Try adding that and let me know if it works. Think i will be pushing that to the repo as well

**Comment by fabrizionastri** [comment]
Yes, it works like a charm, thank you ! A bravo for the nice design.

You may want to add it to the README.md file, or add the `.npmrc` file in the repo directly.

**Comment by BayBreezy** [comment]
OK great! I added it to the repo. Thanks for trying it out on your end.

_"A bravo for the nice design."_ - Thank you :)
